#!/bin/sh -
STATUS=100

while [ $STATUS -eq 100 ]
do
  java -Djavax.net.ssl.trustStore=/opt/app/honeycomb/jssecacerts -jar $(dirname $0)/gnbsim-distribution-1.19.08-SNAPSHOT.jar
  STATUS=$?
  echo "Honeycomb exited with status: $STATUS"
  if [ $STATUS -eq 100 ]
  then
    echo "Restarting..."
  fi
done
